### ISSUE TITLE
Issue with docker build

### ISSUE THREAD

**Issue by anjugopinath** [axkoenig/grasp_refinement#2]
I am getting this error when I execute the command "docker build -t axkoenig/grasp_refinement ." :

![image](https://user-images.githubusercontent.com/4654298/142745941-e2e47388-900a-475d-841c-7dfe96287193.png)

**Comment by axkoenig** [comment]
Hi there, 
thanks for reaching out. As stated in the `README.md` you need to `cd` into the repository you just cloned. The steps are: 
1) `git clone --recursive https://github.com/axkoenig/grasp_refinement.git`
2) `cd grasp_refinement`
3) `docker build -t axkoenig/grasp_refinement .`

**Comment by anjugopinath** [comment]
That worked. Thank You!
