### ISSUE TITLE
Error when testing pre-trained agent

### ISSUE THREAD

**Issue by anjugopinath** [axkoenig/grasp_refinement#3]
I got this error when I executed the command 
"docker-compose run grasp_refinement /bin/bash -c "source /home/catkin_ws/devel/setup.bash; python3 /home/catkin_ws/src/agent/src/main.py --output_dir=/home/.ros/log --train=0 --test_model_path=/home/catkin_ws/src/trained_agents/epsilon+delta_full --all_test_cases=0 --reward_framework=1 --contact_framework=1 --log_name=i_love_robots""

from inside the folder grasp_refinement:

![image](https://user-images.githubusercontent.com/4654298/142774304-66f31c03-e44c-4be5-ab8c-689316f08da0.png)

I get a blank page.
![image](https://user-images.githubusercontent.com/4654298/142774321-84424daa-aa9a-48f2-a8f8-0c13f766a116.png)

**Comment by axkoenig** [comment]
Thanks for raising this issue. I'll look into this asap, hopefully tomorrow :)

**Comment by anjugopinath** [comment]
Thank You!

**Comment by axkoenig** [comment]
I was able to replicate this, sorry about that. A quick fix is simply pulling the image on Dockerhub instead of building it locally.
```bash
# (1) get latest running image from docker hub
docker pull axkoenig/grasp_refinement
cd grasp_refinement
# (2) test a pre-trained agent
docker-compose run grasp_refinement /bin/bash -c "source /home/catkin_ws/devel/setup.bash; python3 /home/catkin_ws/src/agent/src/main.py --output_dir=/home/.ros/log --train=0 --test_model_path=/home/catkin_ws/src/trained_agents/epsilon+delta_full --all_test_cases=0 --reward_framework=1 --contact_framework=1 --log_name=i_love_robots"
# (3) type this into your browser to get graphical output 
localhost:8080/vnc.html
```
I'll investigate what the problem is with the local build. I'm in the midst of interview processes right now, so I may need a bit more time to fix this. But I'm on it! :)

**Comment by axkoenig** [comment]
Hi @anjugopinath, 
my most recent commit fixes the problem of the broken dependency. Please check out the `main` branch and try again. If you continue to have problems, feel free to re-open this issue! 
All the best,
Alex
